"""
_gen_sector_map.py -- Fetches Nifty 500 + Microcap 250 sector/industry data
from NSE India API and writes sector_map.py.

Run manually to regenerate:
    python _gen_sector_map.py
"""
import warnings, json, time
warnings.filterwarnings("ignore")
import requests

def _make_session():
    s = requests.Session()
    s.verify = False
    s.headers.update({
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        "Accept": "application/json, text/plain, */*",
        "Referer": "https://www.nseindia.com/",
        "Accept-Language": "en-US,en;q=0.9",
    })
    s.get("https://www.nseindia.com", timeout=15)
    return s

def fetch_index_sector(session, index_name):
    """Fetch stocks with their industry from a given NSE index."""
    url = f"https://www.nseindia.com/api/equity-stockIndices?index={requests.utils.quote(index_name)}"
    r = session.get(url, timeout=20)
    r.raise_for_status()
    data = r.json().get("data", [])
    result = {}
    for x in data:
        sym = x.get("symbol", "").strip()
        if not sym or sym == index_name:
            continue
        industry = (x.get("meta", {}) or {}).get("industry") or x.get("industry") or ""
        sector   = (x.get("meta", {}) or {}).get("sector")   or x.get("sector")   or ""
        # NSE uses 'industry' at the macro level in most endpoints
        if industry or sector:
            result[sym] = {"sector": sector or industry, "industry": industry or sector}
    return result

def write_sector_map(mapping, path="sector_map.py"):
    lines = [
        '"""',
        "sector_map.py -- Static NSE sector/industry mapping for Nifty 500 + Microcap 250.",
        "Auto-generated by _gen_sector_map.py  —  refresh quarterly.",
        '"""',
        "",
        "# Dict: NSE symbol (no .NS suffix) -> {sector, industry}",
        "SECTOR_MAP: dict = {",
    ]
    for sym in sorted(mapping):
        d = mapping[sym]
        sec = d.get("sector", "").replace("'", "\\'")
        ind = d.get("industry", "").replace("'", "\\'")
        lines.append(f"    '{sym}': {{'sector': '{sec}', 'industry': '{ind}'}},")
    lines += ["}", ""]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Written {len(mapping)} entries to {path}")

if __name__ == "__main__":
    print("Connecting to NSE India...")
    s = _make_session()
    mapping = {}

    for idx in ["NIFTY 500", "NIFTY MICROCAP 250"]:
        print(f"Fetching {idx}...")
        try:
            data = fetch_index_sector(s, idx)
            mapping.update(data)
            print(f"  {len(data)} stocks")
            time.sleep(1)
        except Exception as e:
            print(f"  Failed: {e}")

    if mapping:
        write_sector_map(mapping)
    else:
        print("No data fetched — sector_map.py not written")

