services:
  - type: web
    name: fastapi-website
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    disk:
      name: scanner-cache
      mountPath: /opt/render/project/src/cache
      sizeGB: 1
