"""
sector_map.py -- Static NSE sector / industry mapping for Nifty 500 + Microcap 250.

Each entry: "NSE_SYMBOL" -> {"sector": "...", "industry": "..."}
Symbols are without the .NS suffix.

Refresh with:  python _gen_sector_map.py
"""

SECTOR_MAP: dict = {
    # ── Information Technology ──────────────────────────────────────────────
    "INFY":         {"sector": "Information Technology", "industry": "IT Services"},
    "TCS":          {"sector": "Information Technology", "industry": "IT Services"},
    "WIPRO":        {"sector": "Information Technology", "industry": "IT Services"},
    "HCLTECH":      {"sector": "Information Technology", "industry": "IT Services"},
    "TECHM":        {"sector": "Information Technology", "industry": "IT Services"},
    "LTTS":         {"sector": "Information Technology", "industry": "IT Consulting & Software"},
    "COFORGE":      {"sector": "Information Technology", "industry": "IT Services"},
    "MPHASIS":      {"sector": "Information Technology", "industry": "IT Services"},
    "PERSISTENT":   {"sector": "Information Technology", "industry": "IT Services"},
    "OFSS":         {"sector": "Information Technology", "industry": "IT Services"},
    "BSOFT":        {"sector": "Information Technology", "industry": "IT Services"},
    "CYIENT":       {"sector": "Information Technology", "industry": "IT Consulting & Software"},
    "KPITTECH":     {"sector": "Information Technology", "industry": "IT Consulting & Software"},
    "NEWGEN":       {"sector": "Information Technology", "industry": "IT Consulting & Software"},
    "NETWEB":       {"sector": "Information Technology", "industry": "IT Hardware"},
    "LATENTVIEW":   {"sector": "Information Technology", "industry": "IT Services"},
    "TATAELXSI":    {"sector": "Information Technology", "industry": "IT Consulting & Software"},
    "TATATECH":     {"sector": "Information Technology", "industry": "IT Consulting & Software"},
    "TATACOMM":     {"sector": "Telecom", "industry": "Telecom Services"},
    "SONATSOFTW":   {"sector": "Information Technology", "industry": "IT Services"},
    "MASTEK":       {"sector": "Information Technology", "industry": "IT Services"},
    "RATEGAIN":     {"sector": "Information Technology", "industry": "IT Services"},
    "AURIONPRO":    {"sector": "Information Technology", "industry": "IT Services"},
    "HAPPSTMNDS":   {"sector": "Information Technology", "industry": "IT Services"},
    "ZENSARTECH":   {"sector": "Information Technology", "industry": "IT Services"},
    "DATAMATICS":   {"sector": "Information Technology", "industry": "IT Services"},
    "CIGNITITEC":   {"sector": "Information Technology", "industry": "IT Services"},
    "TANLA":        {"sector": "Information Technology", "industry": "IT Services"},
    "INTELLECT":    {"sector": "Information Technology", "industry": "IT Consulting & Software"},
    "AFFLE":        {"sector": "Information Technology", "industry": "Internet & Software"},
    "MAPMYINDIA":   {"sector": "Information Technology", "industry": "Internet & Software"},
    "SAGILITY":     {"sector": "Information Technology", "industry": "IT Services"},
    "AXISCADES":    {"sector": "Information Technology", "industry": "IT Consulting & Software"},
    "ECLERX":       {"sector": "Information Technology", "industry": "IT Services"},
    "ROUTE":        {"sector": "Information Technology", "industry": "IT Services"},
    "TIMETECHNO":   {"sector": "Information Technology", "industry": "IT Services"},
    "NAUKRI":       {"sector": "Information Technology", "industry": "Internet & Software"},
    "INDIAMART":    {"sector": "Information Technology", "industry": "Internet & Software"},
    "CARTRADE":     {"sector": "Information Technology", "industry": "Internet & Software"},
    "PAYTM":        {"sector": "Financial Services", "industry": "Fintech"},
    "SWIGGY":       {"sector": "Consumer Services", "industry": "Food Delivery"},
    "ETERNAL":      {"sector": "Consumer Services", "industry": "Food Delivery"},
    "POLICYBZR":    {"sector": "Financial Services", "industry": "Insurance Broking"},
    "MEESHO":       {"sector": "Consumer Services", "industry": "E-Commerce"},
    "BLACKBUCK":    {"sector": "Information Technology", "industry": "Logistics Tech"},
    "IXIGO":        {"sector": "Information Technology", "industry": "Travel Tech"},
    "CAPILLARY":    {"sector": "Information Technology", "industry": "IT Services"},
    "CCAVENUE":     {"sector": "Financial Services", "industry": "Fintech"},
    "ZAGGLE":       {"sector": "Financial Services", "industry": "Fintech"},
    "JUSTDIAL":     {"sector": "Information Technology", "industry": "Internet & Software"},
    "NAZARA":       {"sector": "Media & Entertainment", "industry": "Gaming"},
    "TBOTEK":       {"sector": "Information Technology", "industry": "IT Services"},
    "IKS":          {"sector": "Information Technology", "industry": "IT Services"},

    # ── Banking ─────────────────────────────────────────────────────────────
    "HDFCBANK":     {"sector": "Financial Services", "industry": "Private Sector Bank"},
    "ICICIBANK":    {"sector": "Financial Services", "industry": "Private Sector Bank"},
    "SBIN":         {"sector": "Financial Services", "industry": "Public Sector Bank"},
    "KOTAKBANK":    {"sector": "Financial Services", "industry": "Private Sector Bank"},
    "AXISBANK":     {"sector": "Financial Services", "industry": "Private Sector Bank"},
    "BANKBARODA":   {"sector": "Financial Services", "industry": "Public Sector Bank"},
    "BANKINDIA":    {"sector": "Financial Services", "industry": "Public Sector Bank"},
    "FEDERALBNK":   {"sector": "Financial Services", "industry": "Private Sector Bank"},
    "INDUSINDBK":   {"sector": "Financial Services", "industry": "Private Sector Bank"},
    "IDFCFIRSTB":   {"sector": "Financial Services", "industry": "Private Sector Bank"},
    "RBLBANK":      {"sector": "Financial Services", "industry": "Private Sector Bank"},
    "CUB":          {"sector": "Financial Services", "industry": "Private Sector Bank"},
    "KARURVYSYA":   {"sector": "Financial Services", "industry": "Private Sector Bank"},
    "J&KBANK":      {"sector": "Financial Services", "industry": "Public Sector Bank"},
    "MAHABANK":     {"sector": "Financial Services", "industry": "Public Sector Bank"},
    "INDIANB":      {"sector": "Financial Services", "industry": "Public Sector Bank"},
    "IOB":          {"sector": "Financial Services", "industry": "Public Sector Bank"},
    "CENTRALBK":    {"sector": "Financial Services", "industry": "Public Sector Bank"},
    "CANBK":        {"sector": "Financial Services", "industry": "Public Sector Bank"},
    "UCOBANK":      {"sector": "Financial Services", "industry": "Public Sector Bank"},
    "YESBANK":      {"sector": "Financial Services", "industry": "Private Sector Bank"},
    "IDBI":         {"sector": "Financial Services", "industry": "Public Sector Bank"},
    "AUBANK":       {"sector": "Financial Services", "industry": "Private Sector Bank"},
    "BANDHANBNK":   {"sector": "Financial Services", "industry": "Private Sector Bank"},
    "EQUITASBNK":   {"sector": "Financial Services", "industry": "Small Finance Bank"},
    "UJJIVANSFB":   {"sector": "Financial Services", "industry": "Small Finance Bank"},
    "SOUTHBANK":    {"sector": "Financial Services", "industry": "Private Sector Bank"},
    "KTKBANK":      {"sector": "Financial Services", "industry": "Private Sector Bank"},
    "DCBBANK":      {"sector": "Financial Services", "industry": "Private Sector Bank"},
    "TMB":          {"sector": "Financial Services", "industry": "Private Sector Bank"},
    "CSBBANK":      {"sector": "Financial Services", "industry": "Private Sector Bank"},
    "JSFB":         {"sector": "Financial Services", "industry": "Small Finance Bank"},
    "UNIONBANK":    {"sector": "Financial Services", "industry": "Public Sector Bank"},
    "VIJAYA":       {"sector": "Financial Services", "industry": "Public Sector Bank"},

    # ── Finance / NBFC / AMC ────────────────────────────────────────────────
    "BAJFINANCE":   {"sector": "Financial Services", "industry": "Consumer Finance"},
    "BAJAJFINSV":   {"sector": "Financial Services", "industry": "Financial Conglomerate"},
    "CHOLAFIN":     {"sector": "Financial Services", "industry": "Consumer Finance"},
    "M&MFIN":       {"sector": "Financial Services", "industry": "Consumer Finance"},
    "CREDITACC":    {"sector": "Financial Services", "industry": "Microfinance"},
    "MANAPPURAM":   {"sector": "Financial Services", "industry": "Gold Finance"},
    "MUTHOOTFIN":   {"sector": "Financial Services", "industry": "Gold Finance"},
    "POONAWALLA":   {"sector": "Financial Services", "industry": "Consumer Finance"},
    "SHRIRAMFIN":   {"sector": "Financial Services", "industry": "Consumer Finance"},
    "LICHSGFIN":    {"sector": "Financial Services", "industry": "Housing Finance"},
    "CANFINHOME":   {"sector": "Financial Services", "industry": "Housing Finance"},
    "HOMEFIRST":    {"sector": "Financial Services", "industry": "Housing Finance"},
    "AAVAS":        {"sector": "Financial Services", "industry": "Housing Finance"},
    "APTUS":        {"sector": "Financial Services", "industry": "Housing Finance"},
    "FIVESTAR":     {"sector": "Financial Services", "industry": "Consumer Finance"},
    "SBFC":         {"sector": "Financial Services", "industry": "Consumer Finance"},
    "FEDFINA":      {"sector": "Financial Services", "industry": "Consumer Finance"},
    "INDIASHLTR":   {"sector": "Financial Services", "industry": "Housing Finance"},
    "JIOFIN":       {"sector": "Financial Services", "industry": "Financial Services"},
    "TATACAP":      {"sector": "Financial Services", "industry": "Consumer Finance"},
    "HDBFS":        {"sector": "Financial Services", "industry": "Consumer Finance"},
    "IIFL":         {"sector": "Financial Services", "industry": "Wealth Management"},
    "GROWW":        {"sector": "Financial Services", "industry": "Wealth Management"},
    "MOTILALOFS":   {"sector": "Financial Services", "industry": "Wealth Management"},
    "ANGELONE":     {"sector": "Financial Services", "industry": "Stock Broking"},
    "NUVAMA":       {"sector": "Financial Services", "industry": "Wealth Management"},
    "ANANDRATHI":   {"sector": "Financial Services", "industry": "Wealth Management"},
    "360ONE":       {"sector": "Financial Services", "industry": "Wealth Management"},
    "BBTC":         {"sector": "Financial Services", "industry": "Investment Holding"},
    "CGCL":         {"sector": "Financial Services", "industry": "Consumer Finance"},
    "IFCI":         {"sector": "Financial Services", "industry": "Financial Services"},
    "RELIGARE":     {"sector": "Financial Services", "industry": "Financial Services"},
    "SAMMAANCAP":   {"sector": "Financial Services", "industry": "Financial Services"},
    "HDFCAMC":      {"sector": "Financial Services", "industry": "Asset Management"},
    "ICICIAMC":     {"sector": "Financial Services", "industry": "Asset Management"},
    "NAM-INDIA":    {"sector": "Financial Services", "industry": "Asset Management"},
    "UTIAMC":       {"sector": "Financial Services", "industry": "Asset Management"},
    "ABSLAMC":      {"sector": "Financial Services", "industry": "Asset Management"},
    "CAMS":         {"sector": "Financial Services", "industry": "Financial Technology"},
    "KFINTECH":     {"sector": "Financial Services", "industry": "Financial Technology"},
    "CDSL":         {"sector": "Financial Services", "industry": "Depository"},
    "BSE":          {"sector": "Financial Services", "industry": "Stock Exchange"},
    "MCX":          {"sector": "Financial Services", "industry": "Commodity Exchange"},
    "IEX":          {"sector": "Financial Services", "industry": "Power Exchange"},
    "BAJAJHFL":     {"sector": "Financial Services", "industry": "Housing Finance"},
    "BAJAJHLDNG":   {"sector": "Financial Services", "industry": "Investment Holding"},
    "IIFLCAPS":     {"sector": "Financial Services", "industry": "Investment Banking"},
    "CRAMC":        {"sector": "Financial Services", "industry": "Asset Management"},
    "SHAREINDIA":   {"sector": "Financial Services", "industry": "Stock Broking"},
    "PRUDENT":      {"sector": "Financial Services", "industry": "Financial Services"},
    "JMFINANCIL":   {"sector": "Financial Services", "industry": "Investment Banking"},
    "SUNDARMFIN":   {"sector": "Financial Services", "industry": "Consumer Finance"},
    "CHOICEIN":     {"sector": "Financial Services", "industry": "Stock Broking"},
    "CHOLAHLDNG":   {"sector": "Financial Services", "industry": "Financial Conglomerate"},
    "ABCAPITAL":    {"sector": "Financial Services", "industry": "Financial Services"},
    "AADHARHFC":    {"sector": "Financial Services", "industry": "Housing Finance"},
    "PIRAMALFIN":   {"sector": "Financial Services", "industry": "Consumer Finance"},
    "EDELWEISS":    {"sector": "Financial Services", "industry": "Financial Services"},

    # ── Insurance ───────────────────────────────────────────────────────────
    "SBILIFE":      {"sector": "Financial Services", "industry": "Life Insurance"},
    "HDFCLIFE":     {"sector": "Financial Services", "industry": "Life Insurance"},
    "ICICIPRULI":   {"sector": "Financial Services", "industry": "Life Insurance"},
    "LICI":         {"sector": "Financial Services", "industry": "Life Insurance"},
    "NIACL":        {"sector": "Financial Services", "industry": "General Insurance"},
    "GICRE":        {"sector": "Financial Services", "industry": "General Insurance"},
    "ICICIGI":      {"sector": "Financial Services", "industry": "General Insurance"},
    "CANHLIFE":     {"sector": "Financial Services", "industry": "Life Insurance"},
    "STARHEALTH":   {"sector": "Financial Services", "industry": "Health Insurance"},
    "GODIGIT":      {"sector": "Financial Services", "industry": "General Insurance"},
    "MFSL":         {"sector": "Financial Services", "industry": "Life Insurance"},
    "SAILIFE":      {"sector": "Financial Services", "industry": "Financial Services"},
    "NIVABUPA":     {"sector": "Financial Services", "industry": "Health Insurance"},

    # ── Pharmaceuticals ─────────────────────────────────────────────────────
    "SUNPHARMA":    {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "DRREDDY":      {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "CIPLA":        {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "LUPIN":        {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "DIVISLAB":     {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "AUROPHARMA":   {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "ALKEM":        {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "GLAND":        {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "GRANULES":     {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "NATCOPHARM":   {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "AJANTPHARM":   {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "ABBOTINDIA":   {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "PFIZER":       {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "GLAXO":        {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "GLENMARK":     {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "EMCURE":       {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "BIOCON":       {"sector": "Healthcare", "industry": "Biotechnology"},
    "SYNGENE":      {"sector": "Healthcare", "industry": "Biotechnology"},
    "WOCKPHARMA":   {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "CAPLIPOINT":   {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "LAURUSLABS":   {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "NEULANDLAB":   {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "JBCHEPHARM":   {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "PPLPHARMA":    {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "IPCALAB":      {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "ERIS":         {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "JUBLPHARMA":   {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "CONCORDBIO":   {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "TORNTPHARM":   {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "ZYDUSLIFE":    {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "ZYDUSWELL":    {"sector": "Healthcare", "industry": "Consumer Healthcare"},
    "MARKSANS":     {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "SUPRIYA":      {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "SPARC":        {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "AARTIPHARM":   {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "AARTIDRUGS":   {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "BLUEJET":      {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "SUDEEPPHRM":   {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "THYROCARE":    {"sector": "Healthcare", "industry": "Diagnostics"},
    "LALPATHLAB":   {"sector": "Healthcare", "industry": "Diagnostics"},
    "METROPOLIS":   {"sector": "Healthcare", "industry": "Diagnostics"},
    "POLYMED":      {"sector": "Healthcare", "industry": "Medical Devices"},
    "MANKIND":      {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "SHILPAMED":    {"sector": "Healthcare", "industry": "Medical Devices"},
    "ACUTAAS":      {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "JLHL":         {"sector": "Healthcare", "industry": "Diagnostics"},
    "SUDARSCHEM":   {"sector": "Chemicals", "industry": "Specialty Chemicals"},
    "ANTHEM":       {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "NEOGEN":       {"sector": "Healthcare", "industry": "Biotechnology"},
    "AGARWALEYE":   {"sector": "Healthcare", "industry": "Healthcare Services"},
    "PARKHOSPS":    {"sector": "Healthcare", "industry": "Hospital"},
    "HCG":          {"sector": "Healthcare", "industry": "Hospital"},
    "YATHARTH":     {"sector": "Healthcare", "industry": "Hospital"},
    "NH":           {"sector": "Healthcare", "industry": "Hospital"},
    "KIMS":         {"sector": "Healthcare", "industry": "Hospital"},
    "MEDANTA":      {"sector": "Healthcare", "industry": "Hospital"},
    "RAINBOW":      {"sector": "Healthcare", "industry": "Hospital"},
    "APOLLOHOSP":   {"sector": "Healthcare", "industry": "Hospital"},
    "FORTIS":       {"sector": "Healthcare", "industry": "Hospital"},
    "MAXHEALTH":    {"sector": "Healthcare", "industry": "Hospital"},
    "ASTERDM":      {"sector": "Healthcare", "industry": "Hospital"},
    "ALIVUS":       {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "AKUMS":        {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "MEDPLUS":      {"sector": "Healthcare", "industry": "Pharma Retail"},

    # ── Automobile ──────────────────────────────────────────────────────────
    "MARUTI":       {"sector": "Automobile", "industry": "Passenger Vehicles"},
    "M&M":          {"sector": "Automobile", "industry": "Commercial Vehicles"},
    "HEROMOTOCO":   {"sector": "Automobile", "industry": "2 & 3 Wheelers"},
    "BAJAJ-AUTO":   {"sector": "Automobile", "industry": "2 & 3 Wheelers"},
    "EICHERMOT":    {"sector": "Automobile", "industry": "2 & 3 Wheelers"},
    "TVSMOTOR":     {"sector": "Automobile", "industry": "2 & 3 Wheelers"},
    "ASHOKLEY":     {"sector": "Automobile", "industry": "Commercial Vehicles"},
    "ESCORTS":      {"sector": "Automobile", "industry": "Farm & Construction Vehicles"},
    "MOTHERSON":    {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "APOLLOTYRE":   {"sector": "Automobile", "industry": "Tyres & Rubber"},
    "BALKRISIND":   {"sector": "Automobile", "industry": "Tyres & Rubber"},
    "CEATLTD":      {"sector": "Automobile", "industry": "Tyres & Rubber"},
    "MRF":          {"sector": "Automobile", "industry": "Tyres & Rubber"},
    "JKTYRE":       {"sector": "Automobile", "industry": "Tyres & Rubber"},
    "ENDURANCE":    {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "CRAFTSMAN":    {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "JBMA":         {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "UNOMINDA":     {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "GABRIEL":      {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "SUBROS":       {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "JAMNAAUTO":    {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "PRICOLLTD":    {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "SANSERA":      {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "ASKAUTOLTD":   {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "VARROC":       {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "BOSCHLTD":     {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "SCHAEFFLER":   {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "TIINDIA":      {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "TIMKEN":       {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "ZFCVINDIA":    {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "FORCEMOT":     {"sector": "Automobile", "industry": "Commercial Vehicles"},
    "MAHSEAMLES":   {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "MAHSCOOTER":   {"sector": "Automobile", "industry": "2 & 3 Wheelers"},
    "HYUNDAI":      {"sector": "Automobile", "industry": "Passenger Vehicles"},
    "TMCV":         {"sector": "Automobile", "industry": "Commercial Vehicles"},
    "TMPV":         {"sector": "Automobile", "industry": "Passenger Vehicles"},
    "OLAELEC":      {"sector": "Automobile", "industry": "Electric Vehicles"},
    "OLECTRA":      {"sector": "Automobile", "industry": "Electric Vehicles"},
    "EXIDEIND":     {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "LUMAXTECH":    {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "SMLMAH":       {"sector": "Automobile", "industry": "Commercial Vehicles"},
    "FIEMIND":      {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "TI":           {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "BELRISE":      {"sector": "Automobile", "industry": "Auto Ancillaries"},

    # ── Energy / Oil & Gas ──────────────────────────────────────────────────
    "RELIANCE":     {"sector": "Oil & Gas", "industry": "Integrated Oil & Gas"},
    "ONGC":         {"sector": "Oil & Gas", "industry": "Exploration & Production"},
    "BPCL":         {"sector": "Oil & Gas", "industry": "Oil Refining & Marketing"},
    "IOC":          {"sector": "Oil & Gas", "industry": "Oil Refining & Marketing"},
    "HINDPETRO":    {"sector": "Oil & Gas", "industry": "Oil Refining & Marketing"},
    "GAIL":         {"sector": "Oil & Gas", "industry": "Gas Transmission"},
    "MGL":          {"sector": "Oil & Gas", "industry": "City Gas Distribution"},
    "IGL":          {"sector": "Oil & Gas", "industry": "City Gas Distribution"},
    "PETRONET":     {"sector": "Oil & Gas", "industry": "LNG"},
    "MRPL":         {"sector": "Oil & Gas", "industry": "Oil Refining & Marketing"},
    "OIL":          {"sector": "Oil & Gas", "industry": "Exploration & Production"},
    "CHENNPETRO":   {"sector": "Oil & Gas", "industry": "Oil Refining & Marketing"},
    "SPLPETRO":     {"sector": "Oil & Gas", "industry": "Oil Refining & Marketing"},
    "ATGL":         {"sector": "Oil & Gas", "industry": "City Gas Distribution"},
    "GSPL":         {"sector": "Oil & Gas", "industry": "Gas Transmission"},
    "AEGISLOG":     {"sector": "Oil & Gas", "industry": "LPG & CNG"},
    "AEGISVOPAK":   {"sector": "Oil & Gas", "industry": "Terminals & Tanks"},

    # ── Power ────────────────────────────────────────────────────────────────
    "NTPC":         {"sector": "Power", "industry": "Power Generation"},
    "POWERGRID":    {"sector": "Power", "industry": "Power Transmission"},
    "TATAPOWER":    {"sector": "Power", "industry": "Power Generation"},
    "ADANIGREEN":   {"sector": "Power", "industry": "Renewable Energy"},
    "ADANIENSOL":   {"sector": "Power", "industry": "Renewable Energy"},
    "JSWENERGY":    {"sector": "Power", "industry": "Power Generation"},
    "TORNTPOWER":   {"sector": "Power", "industry": "Power Distribution"},
    "NHPC":         {"sector": "Power", "industry": "Hydro Power"},
    "SJVN":         {"sector": "Power", "industry": "Hydro Power"},
    "CESC":         {"sector": "Power", "industry": "Power Distribution"},
    "RPOWER":       {"sector": "Power", "industry": "Power Generation"},
    "SUZLON":       {"sector": "Power", "industry": "Wind Energy"},
    "INOXWIND":     {"sector": "Power", "industry": "Wind Energy"},
    "INOXGREEN":    {"sector": "Power", "industry": "Renewable Energy"},
    "WAAREEENER":   {"sector": "Power", "industry": "Solar Energy"},
    "WAAREERTL":    {"sector": "Power", "industry": "Solar Energy"},
    "KPIGREEN":     {"sector": "Power", "industry": "Solar Energy"},
    "SWSOLAR":      {"sector": "Power", "industry": "Solar Energy"},
    "VIKRAMSOLR":   {"sector": "Power", "industry": "Solar Energy"},
    "WEBELSOLAR":   {"sector": "Power", "industry": "Solar Energy"},
    "UTLSOLAR":     {"sector": "Power", "industry": "Solar Energy"},
    "EMMVEE":       {"sector": "Power", "industry": "Solar Energy"},
    "QPOWER":       {"sector": "Power", "industry": "Renewable Energy"},
    "ACMESOLAR":    {"sector": "Power", "industry": "Solar Energy"},
    "JPPOWER":      {"sector": "Power", "industry": "Power Generation"},
    "RTNINDIA":     {"sector": "Power", "industry": "Power Generation"},
    "RTNPOWER":     {"sector": "Power", "industry": "Power Generation"},
    "NLCINDIA":     {"sector": "Power", "industry": "Power Generation"},
    "IREDA":        {"sector": "Power", "industry": "Renewable Energy Finance"},
    "ATHERENERG":   {"sector": "Power", "industry": "Renewable Energy"},

    # ── Metals & Mining ──────────────────────────────────────────────────────
    "TATASTEEL":    {"sector": "Metals & Mining", "industry": "Steel & Steel Products"},
    "JSWSTEEL":     {"sector": "Metals & Mining", "industry": "Steel & Steel Products"},
    "HINDALCO":     {"sector": "Metals & Mining", "industry": "Aluminium"},
    "SAIL":         {"sector": "Metals & Mining", "industry": "Steel & Steel Products"},
    "VEDL":         {"sector": "Metals & Mining", "industry": "Diversified Metals"},
    "NMDC":         {"sector": "Metals & Mining", "industry": "Iron Ore Mining"},
    "HINDCOPPER":   {"sector": "Metals & Mining", "industry": "Copper"},
    "NATIONALUM":   {"sector": "Metals & Mining", "industry": "Aluminium"},
    "MOIL":         {"sector": "Metals & Mining", "industry": "Manganese Ore"},
    "COALINDIA":    {"sector": "Metals & Mining", "industry": "Coal Mining"},
    "GRAPHITE":     {"sector": "Metals & Mining", "industry": "Graphite Electrodes"},
    "HEG":          {"sector": "Metals & Mining", "industry": "Graphite Electrodes"},
    "JINDALSAW":    {"sector": "Metals & Mining", "industry": "Iron & Steel"},
    "JINDALSTEL":   {"sector": "Metals & Mining", "industry": "Steel & Steel Products"},
    "JSL":          {"sector": "Metals & Mining", "industry": "Stainless Steel"},
    "GPIL":         {"sector": "Metals & Mining", "industry": "Steel & Steel Products"},
    "SHYAMMETL":    {"sector": "Metals & Mining", "industry": "Steel & Steel Products"},
    "JAIBALAJI":    {"sector": "Metals & Mining", "industry": "Steel & Steel Products"},
    "IMFA":         {"sector": "Metals & Mining", "industry": "Ferro Alloys"},
    "WELCORP":      {"sector": "Metals & Mining", "industry": "Steel & Steel Products"},
    "RATNAMANI":    {"sector": "Metals & Mining", "industry": "Steel Pipes & Tubes"},
    "ELECTCAST":    {"sector": "Metals & Mining", "industry": "Iron & Steel"},
    "MIDHANI":      {"sector": "Defence", "industry": "Defence Equipment"},
    "HINDZINC":     {"sector": "Metals & Mining", "industry": "Zinc & Lead"},
    "GMDCLTD":      {"sector": "Metals & Mining", "industry": "Mining"},
    "APLAPOLLO":    {"sector": "Metals & Mining", "industry": "Steel Pipes & Tubes"},
    "NSLNISP":      {"sector": "Metals & Mining", "industry": "Steel & Steel Products"},
    "RAIN":         {"sector": "Chemicals", "industry": "Carbon Products"},
    "GRAVITA":      {"sector": "Metals & Mining", "industry": "Lead Recycling"},
    "GALLANTT":     {"sector": "Metals & Mining", "industry": "Steel & Steel Products"},
    "JAYNECOIND":   {"sector": "Metals & Mining", "industry": "Alloy Steel"},
    "BALUFORGE":    {"sector": "Metals & Mining", "industry": "Forging"},
    "RKFORGE":      {"sector": "Metals & Mining", "industry": "Forging"},

    # ── Capital Goods / Engineering ──────────────────────────────────────────
    "LT":           {"sector": "Capital Goods", "industry": "Infrastructure Conglomerate"},
    "BHEL":         {"sector": "Capital Goods", "industry": "Heavy Electrical Equipment"},
    "SIEMENS":      {"sector": "Capital Goods", "industry": "Industrial Equipment"},
    "ABB":          {"sector": "Capital Goods", "industry": "Electrical Equipment"},
    "BHARATFORG":   {"sector": "Capital Goods", "industry": "Forgings"},
    "HAL":          {"sector": "Defence", "industry": "Aerospace & Defence"},
    "BEL":          {"sector": "Defence", "industry": "Electronics for Defence"},
    "BEML":         {"sector": "Defence", "industry": "Heavy Equipment"},
    "COCHINSHIP":   {"sector": "Defence", "industry": "Shipbuilding"},
    "GRSE":         {"sector": "Defence", "industry": "Shipbuilding"},
    "MAZDOCK":      {"sector": "Defence", "industry": "Shipbuilding"},
    "BDL":          {"sector": "Defence", "industry": "Defence Equipment"},
    "CUMMINSIND":   {"sector": "Capital Goods", "industry": "Industrial Engines"},
    "KEC":          {"sector": "Capital Goods", "industry": "Power Transmission Equipment"},
    "NCC":          {"sector": "Capital Goods", "industry": "Construction"},
    "KPIL":         {"sector": "Capital Goods", "industry": "Construction"},
    "THERMAX":      {"sector": "Capital Goods", "industry": "Industrial Equipment"},
    "ELECON":       {"sector": "Capital Goods", "industry": "Industrial Machinery"},
    "ELGIEQUIP":    {"sector": "Capital Goods", "industry": "Compressors"},
    "KIRLOSENG":    {"sector": "Capital Goods", "industry": "Industrial Engines"},
    "CRISIL":       {"sector": "Financial Services", "industry": "Credit Rating"},
    "ENGINERSIN":   {"sector": "Capital Goods", "industry": "Engineering Services"},
    "DATAPATTNS":   {"sector": "Defence", "industry": "Defence Electronics"},
    "AIAENG":       {"sector": "Capital Goods", "industry": "Mining Tools"},
    "KSB":          {"sector": "Capital Goods", "industry": "Pumps"},
    "TITAGARH":     {"sector": "Capital Goods", "industry": "Railways Equipment"},
    "TRITURBINE":   {"sector": "Capital Goods", "industry": "Turbines"},
    "KIRLOSBROS":   {"sector": "Capital Goods", "industry": "Pumps"},
    "KIRLPNU":      {"sector": "Capital Goods", "industry": "Pneumatics"},
    "TDPOWERSYS":   {"sector": "Capital Goods", "industry": "Electrical Equipment"},
    "GREAVESCOT":   {"sector": "Capital Goods", "industry": "Industrial Engines"},
    "VOLTAMP":      {"sector": "Capital Goods", "industry": "Transformers"},
    "CARBORUNIV":   {"sector": "Capital Goods", "industry": "Abrasives"},
    "ACE":          {"sector": "Capital Goods", "industry": "Cranes"},
    "ATLAS":        {"sector": "Capital Goods", "industry": "Construction Equipment"},
    "CGPOWER":      {"sector": "Capital Goods", "industry": "Electrical Equipment"},
    "POWERINDIA":   {"sector": "Capital Goods", "industry": "Transformers"},
    "HONAUT":       {"sector": "Capital Goods", "industry": "Automation"},
    "SCHNEIDER":    {"sector": "Capital Goods", "industry": "Electrical Equipment"},
    "KAYNES":       {"sector": "Capital Goods", "industry": "Electronics Manufacturing"},
    "SYRMA":        {"sector": "Capital Goods", "industry": "Electronics Manufacturing"},
    "DOMS":         {"sector": "Consumer Goods", "industry": "Stationery"},
    "CARBORUNIV":   {"sector": "Capital Goods", "industry": "Abrasives"},
    "TECHNOEF":     {"sector": "Capital Goods", "industry": "Construction Equipment"},
    "LLOYDSME":     {"sector": "Capital Goods", "industry": "Pipes & Fittings"},
    "LLOYDENGG":    {"sector": "Capital Goods", "industry": "Engineering Services"},
    "LLOYDSENGG":   {"sector": "Capital Goods", "industry": "Engineering Services"},
    "LLOYDSENT":    {"sector": "Capital Goods", "industry": "Consumer Durables"},
    "KINETIC":      {"sector": "Capital Goods", "industry": "Industrial Machinery"},
    "PRAJIND":      {"sector": "Capital Goods", "industry": "Industrial Engineering"},
    "VMM":          {"sector": "Capital Goods", "industry": "Textile Machinery"},
    "RUBICON":      {"sector": "Capital Goods", "industry": "Electronics"},
    "DYNAMATECH":   {"sector": "Capital Goods", "industry": "Industrial Equipment"},
    "POWERMECH":    {"sector": "Capital Goods", "industry": "Power Plant O&M"},
    "SOLARINDS":    {"sector": "Defence", "industry": "Defence Equipment"},

    # ── Cement ───────────────────────────────────────────────────────────────
    "ULTRACEMCO":   {"sector": "Cement & Construction Materials", "industry": "Cement"},
    "SHREECEM":     {"sector": "Cement & Construction Materials", "industry": "Cement"},
    "AMBUJACEM":    {"sector": "Cement & Construction Materials", "industry": "Cement"},
    "ACC":          {"sector": "Cement & Construction Materials", "industry": "Cement"},
    "DALBHARAT":    {"sector": "Cement & Construction Materials", "industry": "Cement"},
    "JKCEMENT":     {"sector": "Cement & Construction Materials", "industry": "Cement"},
    "RAMCOCEM":     {"sector": "Cement & Construction Materials", "industry": "Cement"},
    "NUVOCO":       {"sector": "Cement & Construction Materials", "industry": "Cement"},
    "JSWCEMENT":    {"sector": "Cement & Construction Materials", "industry": "Cement"},
    "INDIACEM":     {"sector": "Cement & Construction Materials", "industry": "Cement"},
    "JKLAKSHMI":    {"sector": "Cement & Construction Materials", "industry": "Cement"},
    "BIRLACORPN":   {"sector": "Cement & Construction Materials", "industry": "Cement"},
    "STARCEMENT":   {"sector": "Cement & Construction Materials", "industry": "Cement"},
    "ORIENTCEM":    {"sector": "Cement & Construction Materials", "industry": "Cement"},
    "RHIM":         {"sector": "Cement & Construction Materials", "industry": "Refractory"},
    "CEMPRO":       {"sector": "Cement & Construction Materials", "industry": "Cement Products"},

    # ── FMCG / Consumer Goods ────────────────────────────────────────────────
    "HINDUNILVR":   {"sector": "FMCG", "industry": "FMCG"},
    "ITC":          {"sector": "FMCG", "industry": "Cigarettes & Tobacco"},
    "BRITANNIA":    {"sector": "FMCG", "industry": "Bakery Products"},
    "NESTLEIND":    {"sector": "FMCG", "industry": "Food Products"},
    "MARICO":       {"sector": "FMCG", "industry": "FMCG"},
    "DABUR":        {"sector": "FMCG", "industry": "FMCG"},
    "GODREJCP":     {"sector": "FMCG", "industry": "FMCG"},
    "COLPAL":       {"sector": "FMCG", "industry": "Personal Care"},
    "EMAMILTD":     {"sector": "FMCG", "industry": "Personal Care"},
    "VBL":          {"sector": "FMCG", "industry": "Beverages"},
    "BIKAJI":       {"sector": "FMCG", "industry": "Packaged Foods"},
    "DEVYANI":      {"sector": "Consumer Services", "industry": "Quick Service Restaurants"},
    "JUBLFOOD":     {"sector": "Consumer Services", "industry": "Quick Service Restaurants"},
    "TATACONSUM":   {"sector": "FMCG", "industry": "Tea & Coffee"},
    "HONASA":       {"sector": "FMCG", "industry": "Personal Care"},
    "PATANJALI":    {"sector": "FMCG", "industry": "FMCG"},
    "AWL":          {"sector": "FMCG", "industry": "Edible Oils"},
    "CCL":          {"sector": "FMCG", "industry": "Beverages"},
    "ZYDUSWELL":    {"sector": "Healthcare", "industry": "Consumer Healthcare"},
    "GILLETTE":     {"sector": "FMCG", "industry": "Personal Care"},
    "GODFRYPHLP":   {"sector": "FMCG", "industry": "Cigarettes & Tobacco"},
    "AVANTIFEED":   {"sector": "FMCG", "industry": "Aquaculture"},
    "HERITGFOOD":   {"sector": "FMCG", "industry": "Dairy"},
    "BECTORFOOD":   {"sector": "FMCG", "industry": "Packaged Foods"},
    "GAEL":         {"sector": "FMCG", "industry": "Diversified"},
    "GOKULAGRO":    {"sector": "FMCG", "industry": "Dairy"},
    "UNITDSPR":     {"sector": "FMCG", "industry": "Spirits & Beverages"},
    "RADICO":       {"sector": "FMCG", "industry": "Spirits & Beverages"},
    "UBL":          {"sector": "FMCG", "industry": "Beer & Beverages"},
    "INDIAGLYCO":   {"sector": "Chemicals", "industry": "Distilleries & Breweries"},
    "MANYAVAR":     {"sector": "Consumer Goods", "industry": "Branded Apparel"},
    "REDTAPE":      {"sector": "Consumer Goods", "industry": "Footwear"},
    "BATAINDIA":    {"sector": "Consumer Goods", "industry": "Footwear"},
    "MNGLMFIN":     {"sector": "Financial Services", "industry": "Consumer Finance"},

    # ── Chemicals ────────────────────────────────────────────────────────────
    "PIDILITE":     {"sector": "Chemicals", "industry": "Adhesives"},
    "SRF":          {"sector": "Chemicals", "industry": "Specialty Chemicals"},
    "DEEPAKNTR":    {"sector": "Chemicals", "industry": "Specialty Chemicals"},
    "NAVINFLUOR":   {"sector": "Chemicals", "industry": "Fluorochemicals"},
    "AARTIIND":     {"sector": "Chemicals", "industry": "Specialty Chemicals"},
    "FLUOROCHEM":   {"sector": "Chemicals", "industry": "Fluorochemicals"},
    "ALKYLAMINE":   {"sector": "Chemicals", "industry": "Specialty Chemicals"},
    "CLEAN":        {"sector": "Chemicals", "industry": "Specialty Chemicals"},
    "AETHER":       {"sector": "Chemicals", "industry": "Specialty Chemicals"},
    "LXCHEM":       {"sector": "Chemicals", "industry": "Specialty Chemicals"},
    "BALAMINES":    {"sector": "Chemicals", "industry": "Specialty Chemicals"},
    "PCBL":         {"sector": "Chemicals", "industry": "Carbon Black"},
    "IONEXCHANG":   {"sector": "Chemicals", "industry": "Specialty Chemicals"},
    "GNFC":         {"sector": "Chemicals", "industry": "Fertilisers & Chemicals"},
    "GSFC":         {"sector": "Chemicals", "industry": "Fertilisers & Chemicals"},
    "DCMSHRIRAM":   {"sector": "Chemicals", "industry": "Fertilisers & Chemicals"},
    "COROMANDEL":   {"sector": "Chemicals", "industry": "Agrochemicals"},
    "BAYERCROP":    {"sector": "Chemicals", "industry": "Agrochemicals"},
    "UPL":          {"sector": "Chemicals", "industry": "Agrochemicals"},
    "SUMICHEM":     {"sector": "Chemicals", "industry": "Agrochemicals"},
    "SHARDACROP":   {"sector": "Chemicals", "industry": "Agrochemicals"},
    "DEEPAKFERT":   {"sector": "Chemicals", "industry": "Fertilisers & Chemicals"},
    "CHAMBLFERT":   {"sector": "Chemicals", "industry": "Fertilisers"},
    "RCF":          {"sector": "Chemicals", "industry": "Fertilisers"},
    "NFL":          {"sector": "Chemicals", "industry": "Fertilisers"},
    "FACT":         {"sector": "Chemicals", "industry": "Fertilisers"},
    "PARADEEP":     {"sector": "Chemicals", "industry": "Fertilisers"},
    "RALLIS":       {"sector": "Chemicals", "industry": "Agrochemicals"},
    "TATACHEM":     {"sector": "Chemicals", "industry": "Diversified Chemicals"},
    "ATUL":         {"sector": "Chemicals", "industry": "Specialty Chemicals"},
    "GHCL":         {"sector": "Chemicals", "industry": "Soda Ash"},
    "STYRENIX":     {"sector": "Chemicals", "industry": "Polymer"},
    "ADVENZYMES":   {"sector": "Chemicals", "industry": "Enzymes"},
    "ALKYLAMINE":   {"sector": "Chemicals", "industry": "Specialty Chemicals"},
    "INOXINDIA":    {"sector": "Chemicals", "industry": "Industrial Gases"},
    "LINDEINDIA":   {"sector": "Chemicals", "industry": "Industrial Gases"},
    "ASIANPAINT":   {"sector": "Paints", "industry": "Paints & Varnishes"},
    "BERGEPAINT":   {"sector": "Paints", "industry": "Paints & Varnishes"},
    "JSWDULUX":     {"sector": "Paints", "industry": "Paints & Varnishes"},
    "INDIGOPNTS":   {"sector": "Paints", "industry": "Paints & Varnishes"},
    "KANSAINER":    {"sector": "Paints", "industry": "Paints & Varnishes"},
    "BORORENEW":    {"sector": "Chemicals", "industry": "Specialty Chemicals"},
    "EMMVEE":       {"sector": "Power", "industry": "Solar Energy"},

    # ── Real Estate ──────────────────────────────────────────────────────────
    "DLF":          {"sector": "Real Estate", "industry": "Real Estate"},
    "GODREJPROP":   {"sector": "Real Estate", "industry": "Real Estate"},
    "PRESTIGE":     {"sector": "Real Estate", "industry": "Real Estate"},
    "BRIGADE":      {"sector": "Real Estate", "industry": "Real Estate"},
    "LODHA":        {"sector": "Real Estate", "industry": "Real Estate"},
    "SOBHA":        {"sector": "Real Estate", "industry": "Real Estate"},
    "OBEROIRLTY":   {"sector": "Real Estate", "industry": "Real Estate"},
    "PHOENIXLTD":   {"sector": "Real Estate", "industry": "Retail & Commercial Real Estate"},
    "ANANTRAJ":     {"sector": "Real Estate", "industry": "Real Estate"},
    "DBREALTY":     {"sector": "Real Estate", "industry": "Real Estate"},
    "SUNTECK":      {"sector": "Real Estate", "industry": "Real Estate"},
    "PURVA":        {"sector": "Real Estate", "industry": "Real Estate"},
    "NESCO":        {"sector": "Real Estate", "industry": "Commercial Real Estate"},
    "TARC":         {"sector": "Real Estate", "industry": "Real Estate"},
    "HEMIPROP":     {"sector": "Real Estate", "industry": "Real Estate"},
    "LOTUSDEV":     {"sector": "Real Estate", "industry": "Real Estate"},
    "SAMHI":        {"sector": "Hospitality", "industry": "Hotels"},
    "JUBLINGREA":   {"sector": "Real Estate", "industry": "Real Estate"},
    "GODREJIND":    {"sector": "Consumer Goods", "industry": "Diversified"},

    # ── Hotels / Hospitality ─────────────────────────────────────────────────
    "INDHOTEL":     {"sector": "Hospitality", "industry": "Hotels"},
    "LEMONTREE":    {"sector": "Hospitality", "industry": "Hotels"},
    "THELEELA":     {"sector": "Hospitality", "industry": "Hotels"},
    "CHALET":       {"sector": "Hospitality", "industry": "Hotels"},
    "EIHOTEL":      {"sector": "Hospitality", "industry": "Hotels"},
    "ITCHOTELS":    {"sector": "Hospitality", "industry": "Hotels"},
    "JSLHL":        {"sector": "Hospitality", "industry": "Hotels"},
    "TAJGVK":       {"sector": "Hospitality", "industry": "Hotels"},
    "WESTLIFE":     {"sector": "Consumer Services", "industry": "Quick Service Restaurants"},
    "TRAVELFOOD":   {"sector": "Consumer Services", "industry": "Food Services"},
    "WEWORK":       {"sector": "Real Estate", "industry": "Co-working Spaces"},
    "AWFIS":        {"sector": "Real Estate", "industry": "Co-working Spaces"},
    "SMARTWORKS":   {"sector": "Real Estate", "industry": "Co-working Spaces"},

    # ── Telecom ───────────────────────────────────────────────────────────────
    "BHARTIARTL":   {"sector": "Telecom", "industry": "Telecom Services"},
    "BHARTIHEXA":   {"sector": "Telecom", "industry": "Telecom Services"},
    "IDEA":         {"sector": "Telecom", "industry": "Telecom Services"},
    "INDUSTOWER":   {"sector": "Telecom", "industry": "Telecom Towers"},
    "TEJASNET":     {"sector": "Telecom", "industry": "Telecom Equipment"},
    "HFCL":         {"sector": "Telecom", "industry": "Telecom Equipment"},
    "STLTECH":      {"sector": "Telecom", "industry": "Fibre Optics"},
    "TTML":         {"sector": "Telecom", "industry": "Telecom Services"},
    "ITI":          {"sector": "Telecom", "industry": "Telecom Equipment"},
    "RAILTEL":      {"sector": "Information Technology", "industry": "IT Services"},
    "OPTIEMUS":     {"sector": "Telecom", "industry": "Telecom Equipment"},

    # ── Consumer Durables / Electronics ──────────────────────────────────────
    "HAVELLS":      {"sector": "Consumer Durables", "industry": "Electrical Equipment"},
    "POLYCAB":      {"sector": "Consumer Durables", "industry": "Cables & Wires"},
    "DIXON":        {"sector": "Consumer Durables", "industry": "Electronics Manufacturing"},
    "AMBER":        {"sector": "Consumer Durables", "industry": "Air Conditioning"},
    "BLUESTARCO":   {"sector": "Consumer Durables", "industry": "Air Conditioning"},
    "VOLTAS":       {"sector": "Consumer Durables", "industry": "Air Conditioning"},
    "CROMPTON":     {"sector": "Consumer Durables", "industry": "Electrical Consumer Goods"},
    "KEI":          {"sector": "Consumer Durables", "industry": "Cables & Wires"},
    "FINCABLES":    {"sector": "Consumer Durables", "industry": "Cables & Wires"},
    "RRKABEL":      {"sector": "Consumer Durables", "industry": "Cables & Wires"},
    "VGUARD":       {"sector": "Consumer Durables", "industry": "Electrical Consumer Goods"},
    "TITAN":        {"sector": "Consumer Durables", "industry": "Watches & Accessories"},
    "WHIRLPOOL":    {"sector": "Consumer Durables", "industry": "White Goods"},
    "LGEINDIA":     {"sector": "Consumer Durables", "industry": "Consumer Electronics"},
    "CPPLUS":       {"sector": "Consumer Durables", "industry": "Surveillance Systems"},
    "IFBIND":       {"sector": "Consumer Durables", "industry": "White Goods"},
    "SURYAROSNI":   {"sector": "Consumer Durables", "industry": "Lighting"},
    "LENSKART":     {"sector": "Consumer Goods", "industry": "Eyewear"},
    "NYKAA":        {"sector": "Consumer Goods", "industry": "Beauty & Personal Care"},
    "FIRSTCRY":     {"sector": "Consumer Goods", "industry": "Baby & Kids Retail"},
    "CAMPUS":       {"sector": "Consumer Goods", "industry": "Footwear"},
    "RELAXO":       {"sector": "Consumer Goods", "industry": "Footwear"},
    "CELLO":        {"sector": "Consumer Goods", "industry": "Consumer Products"},
    "SAFARI":       {"sector": "Consumer Goods", "industry": "Luggage"},
    "VIPIND":       {"sector": "Consumer Goods", "industry": "Luggage"},
    "EUREKAFORB":   {"sector": "Consumer Durables", "industry": "Water Purifiers"},

    # ── Retail ────────────────────────────────────────────────────────────────
    "TRENT":        {"sector": "Retail", "industry": "Retail"},
    "DMART":        {"sector": "Retail", "industry": "Supermarkets"},
    "V2RETAIL":     {"sector": "Retail", "industry": "Retail"},
    "VMART":        {"sector": "Retail", "industry": "Retail"},
    "PAGEIND":      {"sector": "Textiles", "industry": "Innerwear & Sleepwear"},

    # ── Jewellery & Luxury ───────────────────────────────────────────────────
    "KALYANKJIL":   {"sector": "Consumer Goods", "industry": "Jewellery"},
    "SENCO":        {"sector": "Consumer Goods", "industry": "Jewellery"},
    "PNGJL":        {"sector": "Consumer Goods", "industry": "Jewellery"},
    "VAIBHAVGBL":   {"sector": "Consumer Goods", "industry": "Jewellery"},
    "PCJEWELLER":   {"sector": "Consumer Goods", "industry": "Jewellery"},
    "SKYGOLD":      {"sector": "Consumer Goods", "industry": "Jewellery"},
    "THANGAMAYL":   {"sector": "Consumer Goods", "industry": "Jewellery"},
    "ETHOS":        {"sector": "Consumer Goods", "industry": "Luxury Watches"},
    "BLUESTONE":    {"sector": "Consumer Goods", "industry": "Jewellery"},

    # ── Textiles & Apparel ───────────────────────────────────────────────────
    "KPRMILL":      {"sector": "Textiles", "industry": "Textile"},
    "WELSPUNLIV":   {"sector": "Textiles", "industry": "Home Textiles"},
    "ARVIND":       {"sector": "Textiles", "industry": "Textile"},
    "ARVINDFASN":   {"sector": "Textiles", "industry": "Branded Apparel"},
    "KITEX":        {"sector": "Textiles", "industry": "Garments"},
    "TRIDENT":      {"sector": "Textiles", "industry": "Textile"},
    "RAYMONDLSL":   {"sector": "Textiles", "industry": "Textile"},
    "SFL":          {"sector": "Textiles", "industry": "Specialty Films"},
    "SAPPHIRE":     {"sector": "Textiles", "industry": "Textile"},
    "SSFL":         {"sector": "Textiles", "industry": "Textile"},

    # ── Infrastructure & Construction ────────────────────────────────────────
    "IRB":          {"sector": "Infrastructure", "industry": "Roads & Highways"},
    "ASHOKA":       {"sector": "Infrastructure", "industry": "Roads & Highways"},
    "KNRCON":       {"sector": "Infrastructure", "industry": "Roads & Highways"},
    "PNCINFRA":     {"sector": "Infrastructure", "industry": "Roads & Highways"},
    "HCC":          {"sector": "Infrastructure", "industry": "Construction"},
    "DBL":          {"sector": "Infrastructure", "industry": "Roads & Highways"},
    "HGINFRA":      {"sector": "Infrastructure", "industry": "Roads & Highways"},
    "NBCC":         {"sector": "Infrastructure", "industry": "Construction"},
    "RVNL":         {"sector": "Infrastructure", "industry": "Railways Construction"},
    "IRCON":        {"sector": "Infrastructure", "industry": "Railways Construction"},
    "AFCONS":       {"sector": "Infrastructure", "industry": "Construction"},
    "ENGINERSIN":   {"sector": "Capital Goods", "industry": "Engineering Services"},
    "HUDCO":        {"sector": "Infrastructure", "industry": "Housing Finance"},
    "PFC":          {"sector": "Financial Services", "industry": "Power Finance"},
    "RECLTD":       {"sector": "Financial Services", "industry": "Power Finance"},
    "LTM":          {"sector": "Capital Goods", "industry": "Heavy Engineering"},
    "LTF":          {"sector": "Financial Services", "industry": "Consumer Finance"},
    "JSWINFRA":     {"sector": "Infrastructure", "industry": "Ports & Shipping"},
    "ADANIPORTS":   {"sector": "Infrastructure", "industry": "Ports & Shipping"},
    "GPPL":         {"sector": "Infrastructure", "industry": "Ports & Shipping"},

    # ── Logistics / Transport ─────────────────────────────────────────────────
    "BLUEDART":     {"sector": "Transportation & Logistics", "industry": "Courier & Delivery"},
    "DELHIVERY":    {"sector": "Transportation & Logistics", "industry": "Logistics"},
    "CONCOR":       {"sector": "Transportation & Logistics", "industry": "Logistics"},
    "IRCTC":        {"sector": "Transportation & Logistics", "industry": "Travel & Tourism"},
    "IRFC":         {"sector": "Financial Services", "industry": "Railway Finance"},
    "RITES":        {"sector": "Capital Goods", "industry": "Engineering Services"},
    "QUESS":        {"sector": "Consumer Services", "industry": "Staffing"},
    "TVSSCS":       {"sector": "Transportation & Logistics", "industry": "Logistics"},
    "AEGISLOG":     {"sector": "Oil & Gas", "industry": "LPG & CNG"},

    # ── Aviation ──────────────────────────────────────────────────────────────
    "INDIGO":       {"sector": "Transportation & Logistics", "industry": "Airline"},
    "GMRAIRPORT":   {"sector": "Infrastructure", "industry": "Airports"},

    # ── Media & Entertainment ────────────────────────────────────────────────
    "SUNTV":        {"sector": "Media & Entertainment", "industry": "Broadcasting"},
    "ZEEL":         {"sector": "Media & Entertainment", "industry": "Broadcasting"},
    "SAREGAMA":     {"sector": "Media & Entertainment", "industry": "Music"},
    "PVRINOX":      {"sector": "Media & Entertainment", "industry": "Multiplex"},
    "TIPSMUSIC":    {"sector": "Media & Entertainment", "industry": "Music"},
    "NETWORK18":    {"sector": "Media & Entertainment", "industry": "Broadcasting"},

    # ── Cables / Pipes ───────────────────────────────────────────────────────
    "SUPREMEIND":   {"sector": "Consumer Durables", "industry": "Plastic Pipes"},
    "ASTRAL":       {"sector": "Consumer Durables", "industry": "Plastic Pipes"},
    "FINPIPE":      {"sector": "Consumer Durables", "industry": "Plastic Pipes"},
    "ASHAPURMIN":   {"sector": "Chemicals", "industry": "Minerals"},
    "APARINDS":     {"sector": "Capital Goods", "industry": "Cables & Wires"},
    "GVT&D":        {"sector": "Capital Goods", "industry": "Power Transmission"},

    # ── Paper / Packaging ────────────────────────────────────────────────────
    "JKPAPER":      {"sector": "Paper & Forest Products", "industry": "Paper"},
    "EPL":          {"sector": "Packaging", "industry": "Flexible Packaging"},
    "CENTURYPLY":   {"sector": "Forest Materials", "industry": "Plywood"},
    "SHAILY":       {"sector": "Packaging", "industry": "Plastic Packaging"},

    # ── Food Processing / Agri ───────────────────────────────────────────────
    "RENUKA":       {"sector": "FMCG", "industry": "Sugar"},
    "EIDPARRY":     {"sector": "FMCG", "industry": "Sugar"},
    "BALRAMCHIN":   {"sector": "FMCG", "industry": "Sugar"},
    "KRBL":         {"sector": "FMCG", "industry": "Rice"},
    "LTFOODS":      {"sector": "FMCG", "industry": "Rice"},
    "CASTROLIND":   {"sector": "Oil & Gas", "industry": "Lubricants"},
    "GOKEX":        {"sector": "FMCG", "industry": "Food Processing"},
    "MANORAMA":     {"sector": "FMCG", "industry": "Edible Oils"},
    "SAATVIKGL":    {"sector": "Consumer Services", "industry": "Restaurants"},
    "PICCADIL":     {"sector": "FMCG", "industry": "Spirits & Beverages"},
    "JYOTHYLAB":    {"sector": "FMCG", "industry": "Home Care"},

    # ── Shipping ─────────────────────────────────────────────────────────────
    "GESHIP":       {"sector": "Transportation & Logistics", "industry": "Shipping"},
    "SCI":          {"sector": "Transportation & Logistics", "industry": "Shipping"},
    "MMTC":         {"sector": "Trading", "industry": "Trading"},

    # ── Diversified / Conglomerate ────────────────────────────────────────────
    "ADANIENT":     {"sector": "Diversified", "industry": "Diversified"},
    "GRASIM":       {"sector": "Diversified", "industry": "Diversified"},
    "ITC":          {"sector": "FMCG", "industry": "Cigarettes & Tobacco"},
    "M&M":          {"sector": "Automobile", "industry": "Diversified"},
    "ABDL":         {"sector": "Diversified", "industry": "Diversified"},
    "ABREL":        {"sector": "Diversified", "industry": "Diversified"},
    "TATAINVEST":   {"sector": "Financial Services", "industry": "Investment Holding"},
    "GODREJIND":    {"sector": "Consumer Goods", "industry": "Diversified"},
    "SWANCORP":     {"sector": "Diversified", "industry": "Diversified"},
    "NAVA":         {"sector": "Diversified", "industry": "Diversified"},
    "SARDAEN":      {"sector": "Metals & Mining", "industry": "Diversified Metals"},

    # ── Other / Miscellaneous ─────────────────────────────────────────────────
    "3MINDIA":      {"sector": "Capital Goods", "industry": "Specialty Products"},
    "CARBORUNIV":   {"sector": "Capital Goods", "industry": "Abrasives"},
    "ASTRAMICRO":   {"sector": "Defence", "industry": "Defence Electronics"},
    "WABAG":        {"sector": "Capital Goods", "industry": "Water Treatment"},
    "IONEXCHANG":   {"sector": "Chemicals", "industry": "Specialty Chemicals"},
    "CMSINFO":      {"sector": "Financial Services", "industry": "Cash Management"},
    "BLS":          {"sector": "Consumer Services", "industry": "E-Governance"},
    "INDGN":        {"sector": "Consumer Services", "industry": "E-Governance"},
    "TBOTEK":       {"sector": "Information Technology", "industry": "IT Services"},
    "PGEL":         {"sector": "Capital Goods", "industry": "Electrical Equipment"},
    "EMBDL":        {"sector": "Chemicals", "industry": "Specialty Chemicals"},
    "ENRIN":        {"sector": "Oil & Gas", "industry": "Energy"},
    "HSCL":         {"sector": "Infrastructure", "industry": "Construction"},
    "IGIL":         {"sector": "Infrastructure", "industry": "Construction"},
    "AIIL":         {"sector": "Capital Goods", "industry": "Industrial Equipment"},
    "MAZMFIN":      {"sector": "Financial Services", "industry": "Consumer Finance"},
    "USHAMART":     {"sector": "Metals & Mining", "industry": "Steel & Steel Products"},
    "PENNANT":      {"sector": "Information Technology", "industry": "IT Services"},
    "STYL":         {"sector": "Textiles", "industry": "Synthetic Fibres"},
    "PUPILMESH":    {"sector": "Information Technology", "industry": "IT Services"},
    "ENTERO":       {"sector": "Healthcare", "industry": "Pharma Distribution"},
    "MEDPLUSHE":    {"sector": "Healthcare", "industry": "Pharma Retail"},
    "JAINREC":      {"sector": "Metals & Mining", "industry": "Recycling"},
    "SIGNATURE":    {"sector": "Financial Services", "industry": "Consumer Finance"},
    "JWL":          {"sector": "Consumer Goods", "industry": "Jewellery"},
    "SKFINDIA":     {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "SKFINDUS":     {"sector": "Capital Goods", "industry": "Bearings"},
    "HIKAL":        {"sector": "Chemicals", "industry": "Specialty Chemicals"},
    "PRSMJOHNSN":   {"sector": "Consumer Goods", "industry": "Printing"},
    "MSTCLTD":      {"sector": "Trading", "industry": "E-Commerce"},
    "GOKALDAS":     {"sector": "Textiles", "industry": "Garments"},
    "LUPIN":        {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "APCOTEXIND":   {"sector": "Textiles", "industry": "Yarn"},
    "MTARTECH":     {"sector": "Defence", "industry": "Precision Engineering"},
    "PENIND":       {"sector": "Capital Goods", "industry": "Metal Pipes"},
    "SUPRIYA":      {"sector": "Healthcare", "industry": "Pharmaceuticals"},
    "CUPID":        {"sector": "Healthcare", "industry": "Medical Devices"},
    "KRITI":        {"sector": "Consumer Durables", "industry": "Plastic Pipes"},
    "KPRMILL":      {"sector": "Textiles", "industry": "Textile"},
    "TEXRAIL":      {"sector": "Capital Goods", "industry": "Railways Equipment"},
    "TRANSRAILL":   {"sector": "Capital Goods", "industry": "Railways Equipment"},
    "TITAGARH":     {"sector": "Capital Goods", "industry": "Railways Equipment"},
    "RITCO":        {"sector": "Transportation & Logistics", "industry": "Logistics"},
    "CHORDIA":      {"sector": "Chemicals", "industry": "Specialty Chemicals"},
    "AWL":          {"sector": "FMCG", "industry": "Edible Oils"},
    "MNGLMFIN":     {"sector": "Financial Services", "industry": "Consumer Finance"},
    "GOKEX":        {"sector": "FMCG", "industry": "Food Processing"},
    "THOMASCOOK":   {"sector": "Consumer Services", "industry": "Travel & Tourism"},
    "KAJARIACER":   {"sector": "Consumer Goods", "industry": "Ceramics & Tiles"},
    "CERA":         {"sector": "Consumer Goods", "industry": "Sanitaryware"},
    "JYOTICNC":     {"sector": "Capital Goods", "industry": "Machine Tools"},
    "SKIPPER":      {"sector": "Capital Goods", "industry": "Transmission Towers"},
    "SHAKTIPUMP":   {"sector": "Capital Goods", "industry": "Pumps"},
    "BANCOINDIA":   {"sector": "Capital Goods", "industry": "Textile Machinery"},
    "GOKLDAS":      {"sector": "Textiles", "industry": "Garments"},
    "OSWAL":        {"sector": "Consumer Goods", "industry": "Consumer Products"},
    "OSWALPUMPS":   {"sector": "Capital Goods", "industry": "Pumps"},
    "ICIL":         {"sector": "Textiles", "industry": "Textile"},
    "ALOKINDS":     {"sector": "Textiles", "industry": "Textile"},
    "CORONA":       {"sector": "Consumer Goods", "industry": "Consumer Products"},
    "ELLEN":        {"sector": "Consumer Goods", "industry": "Consumer Products"},
    "GKWLTD":       {"sector": "Capital Goods", "industry": "Forgings"},
    "BAJAJELEC":    {"sector": "Consumer Durables", "industry": "Electrical Consumer Goods"},
    "MINDACORP":    {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "JKLAKSHMI":    {"sector": "Cement & Construction Materials", "industry": "Cement"},
    "REFEX":        {"sector": "Energy", "industry": "Energy Trading"},
    "ARE&M":        {"sector": "Power", "industry": "Energy Meters"},
    "MNGLMFIN":     {"sector": "Financial Services", "industry": "Consumer Finance"},
    "LOTUSDEV":     {"sector": "Real Estate", "industry": "Real Estate"},
    "TARIL":        {"sector": "Capital Goods", "industry": "Transformers"},
    "TECHNOE":      {"sector": "Capital Goods", "industry": "Engineering"},
    "JYOTICNC":     {"sector": "Capital Goods", "industry": "Machine Tools"},
    "NAUKRI":       {"sector": "Information Technology", "industry": "Internet Services"},
    "NYCIL":        {"sector": "Chemicals", "industry": "Specialty Chemicals"},
    "GMMPFAUDLR":   {"sector": "Capital Goods", "industry": "Compressors"},
    "JKPAPER":      {"sector": "Paper & Forest Products", "industry": "Paper"},
    "ISGEC":        {"sector": "Capital Goods", "industry": "Industrial Equipment"},
    "SANDUMA":      {"sector": "Capital Goods", "industry": "Bearings"},
    "INOXINDIA":    {"sector": "Chemicals", "industry": "Industrial Gases"},
    "EMIL":         {"sector": "Capital Goods", "industry": "Engineering"},
    "STRTECH":      {"sector": "Telecom", "industry": "Telecom Equipment"},
    "DIACABS":      {"sector": "Consumer Durables", "industry": "Cables & Wires"},
    "EIEL":         {"sector": "Capital Goods", "industry": "Cables & Wires"},
    "AVALON":       {"sector": "Capital Goods", "industry": "Electronics Manufacturing"},
    "AXISCADES":    {"sector": "Information Technology", "industry": "IT Consulting & Software"},
    "AZAD":         {"sector": "Capital Goods", "industry": "Engineering"},
    "BLACKBUCK":    {"sector": "Information Technology", "industry": "Logistics Tech"},
    "BBOX":         {"sector": "Information Technology", "industry": "IT Services"},
    "CRIZAC":       {"sector": "Consumer Services", "industry": "Immigration Services"},
    "VIYASH":       {"sector": "Infrastructure", "industry": "Construction"},
    "JSLL":         {"sector": "Infrastructure", "industry": "Roads & Highways"},
    "SFLNSE":       {"sector": "Textiles", "industry": "Specialty Films"},
    "PFOCUS":       {"sector": "Information Technology", "industry": "IT Services"},
    "RUBICON":      {"sector": "Capital Goods", "industry": "Electronics"},
    "PRIVISCL":     {"sector": "Information Technology", "industry": "Data Analytics"},
    "CRAMC":        {"sector": "Financial Services", "industry": "Asset Management"},
    "TSFINV":       {"sector": "Financial Services", "industry": "Investment Holding"},
    "WAKEFIT":      {"sector": "Consumer Goods", "industry": "Furniture"},
    "SANSERA":      {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "ANUP":         {"sector": "Capital Goods", "industry": "Heat Exchangers"},
    "APLLTD":       {"sector": "Textiles", "industry": "Garments"},
    "APOLLO":       {"sector": "Consumer Durables", "industry": "Cables & Wires"},
    "MINIATUREBUL": {"sector": "Capital Goods", "industry": "Industrial Equipment"},
    "LOTUSDEV":     {"sector": "Real Estate", "industry": "Real Estate"},
    "SUNTECK":      {"sector": "Real Estate", "industry": "Real Estate"},
    "CAPILLARY":    {"sector": "Information Technology", "industry": "Retail Tech"},
    "CCAVENUE":     {"sector": "Financial Services", "industry": "Payment Gateway"},
    "ATHENE":       {"sector": "Power", "industry": "Renewable Energy"},
    "SEPC":         {"sector": "Capital Goods", "industry": "Engineering Services"},
    "NARAYANAMED":  {"sector": "Healthcare", "industry": "Hospital"},
    "ZAGGLE":       {"sector": "Financial Services", "industry": "Fintech"},
    "ENTERO":       {"sector": "Healthcare", "industry": "Pharma Distribution"},
    "HOUS2":        {"sector": "Financial Services", "industry": "Housing Finance"},
    "SFLHOSE":      {"sector": "Capital Goods", "industry": "Industrial Equipment"},
    "GODREJIND":    {"sector": "Consumer Goods", "industry": "Diversified"},
    "MRPL":         {"sector": "Oil & Gas", "industry": "Oil Refining & Marketing"},
    "PENWIND":      {"sector": "Power", "industry": "Wind Energy"},
    "MOSCHIP":      {"sector": "Information Technology", "industry": "Semiconductors"},
    "PENIN":        {"sector": "Capital Goods", "industry": "Pipes"},
    "COSMOFILM":    {"sector": "Chemicals", "industry": "Specialty Films"},
    "INDIGOPNTS":   {"sector": "Paints", "industry": "Paints & Varnishes"},
    "AVL":          {"sector": "Power", "industry": "Renewable Energy"},
    "MGAMR":        {"sector": "Capital Goods", "industry": "Industrial Equipment"},
    "AEQUS":        {"sector": "Automobile", "industry": "Auto Ancillaries"},
    "PTCIL":        {"sector": "Power", "industry": "Power Trading"},
    "PTC":          {"sector": "Power", "industry": "Power Trading"},
    "SWANCORP":     {"sector": "Diversified", "industry": "Diversified"},
    # Microcap extras
    "CMSINFO":      {"sector": "Financial Services", "industry": "Cash Management"},
    "NAZARA":       {"sector": "Media & Entertainment", "industry": "Gaming"},
    "Network18":    {"sector": "Media & Entertainment", "industry": "Broadcasting"},
    "IXIGO":        {"sector": "Information Technology", "industry": "Travel Tech"},
    "SAATVIKGL":    {"sector": "Consumer Services", "industry": "Restaurants"},
    "MEDPLUS":      {"sector": "Healthcare", "industry": "Pharma Retail"},
    "KSCL":         {"sector": "Chemicals", "industry": "Agrochemicals"},
    "JLHL":         {"sector": "Healthcare", "industry": "Diagnostics"},
    "RAIN":         {"sector": "Chemicals", "industry": "Carbon Products"},
    "GNFC":         {"sector": "Chemicals", "industry": "Fertilisers & Chemicals"},
    "GSFC":         {"sector": "Chemicals", "industry": "Fertilisers & Chemicals"},
}

